### ISSUE TITLE
Info.plist  from Amazon

### ISSUE THREAD

**Issue by jamesbondo** [driftyco/deploy-tutorial#3]
So I was trying to " add an exclusion rule for AWS S3 servers", but where should we add it? It didn't seem I have a Info.plist in my app folder? What is it? Where is it?

**Comment by Fuiste** [comment]
@jamesbondo this repo is actually _very_ old and no longer reflects the state of the Ionic Platform. 

For assistance setting up Deploy I'd check out the [official docs](http://docs.ionic.io/docs/deploy-overview)

**Comment by jamesbondo** [comment]
that's where i got this thing from..

**Comment by ericb** [comment]
@jamesbondo It's actually named based on your app name: `
platforms/ios/MyApp/MyApp-Info.plist`
